function raw_data = importdata(workbookFile, sheetName, range)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   cell array.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.%
% Example:
%   outputedit1 = importfile('output_edit.xlsx','output_edit','A2:AK72745');
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/03/23 13:55:37

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If no range is specified, read all data
if nargin <= 2 || isempty(range)
    range = '';
end

%% Import the data
[~, ~, raw_data] = xlsread(workbookFile, sheetName, range);
raw_data(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw_data)) = {''};

